import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chat-Auth",
  description: "Generated by create next app",
};

export default function ClientLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main>{children}</main>;
}
